import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import { homePath, ticketsPath } from '@/path';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <nav className="back fixed top-0 right-0 left-0 z-20 flex w-full justify-between border-b py-2.5 backdrop-blur">
                    <div>
                        <Link href={homePath()} className="text-lg font-bold">
                            Home
                        </Link>
                    </div>
                    <div>
                        <Link href={ticketsPath()}>Tickets</Link>
                    </div>
                </nav>
                <main className="flex min-h-screen flex-1 flex-col overflow-x-hidden overflow-y-auto px-8 py-24">
                    {children}
                </main>
            </body>
        </html>
    );
}
